server:
    port: 6666
spring:
    rabbitmq:
#        addresses:
        username: guest
        password: guest
        virtual-host: /
        host: 192.168.1.188
        port: 5672
        publisher-confirm-type: correlated

    application:
        name: rabbitmq-spring-boot-order
    datasource:
        url: jdbc:mysql://192.168.1.188:3306/rabbitmq
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: root

mybatis:
    mapper-locations: classpath:/mapper/*.xml
    config-location: classpath:/mybatis-config.xml